# Generated by Django 3.0.3 on 2021-01-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_quizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('messages', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam', models.IntegerField(primary_key=True, serialize=False)),
                ('section1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section1', to='quiz_api.Quiz')),
                ('section2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section2', to='quiz_api.Quiz')),
                ('section3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section3', to='quiz_api.Quiz')),
            ],
        ),
    ]
