# Generated by Django 3.0.3 on 2021-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_exam_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
